name: sunny_core_widgets
version: 0.3.2+1
homepage: https://github.com/SunnyApp/sunny_core_widgets
description: Core widgets used by Sunny
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  avoid_keyboard: ^0.3.0
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  intl: ^0.17.0
  logging: ^1.0.2
  material_segmented_control: ^3.1.2
  permission_handler: ^10.2.0
  provider: ^6.0.3
  responsive_builder: ^0.4.2
  timeago: ^3.2.2
  modal_bottom_sheet: ^2.1.2
  expanding_cards: 
    git: 
      url: git@github.com:SunnyApp/expanding_cards
      ref: trippi_app
  info_x: 
    git: 
      url: git@github.com:ericmartineau/info_x
      ref: trippi_app
  flexidate: 
    git: 
      url: git@github.com:TrippiApp/flexidate
      ref: trippi_app
  sunny_platform_widgets: 
    git: 
      url: git@github.com:SunnyApp/flutter_platform_widgets
      ref: trippi_app
  flutter_screen_scaling: 
    git: 
      url: git@github.com:SunnyApp/flutter_screen_scaling
      ref: trippi_app
  sunny_essentials: 
    git: 
      url: git@github.com:ericmartineau/sunny_essentials.git
      ref: trippi_app
  sunny_fluro: 
    git: 
      url: git@github.com:SunnyApp/fluro
      ref: trippi_app
  sunny_sdk_core: 
    git: 
      url: git@github.com:SunnyApp/sunny_sdk_core.git
      ref: trippi_app
  dartxx: 
    git: 
      url: git@github.com:ericmartineau/dartxx.git
      ref: trippi_app
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
