name: sunny_core_widgets
version: 0.1.1+11
homepage: https://github.com/SunnyApp/sunny_core_widgets
description: Core widgets used by Sunny
environment: 
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'
dependencies: 
  provider: ^4.3.2+2
  sunny_dart: ^0.5.8+2
  permission_handler: ^5.0.1+1
  flutter_platform_widgets: 0.70.2
  material_segmented_control: ^2.1.0+1
  logging: any
  flutter_screen_scaling:
    path: ../flutter_screen_scaling
  expanding_cards:
    path: ../expanding_cards

  flutter_degen:
    path: ../flutter_degen
  fluro:
    path: ../fluro
  sunny_sdk_core:
    path: ../sunny_sdk_core
  flutter: 
    sdk: flutter
dependency_overrides:
#  flutter_platform_widgets:
#    path: ../flutter_platform_widgets
  waypoints:
    path: ../sunny_entities/waypoints
  sunny_sdk_core:
    path: ../sunny_sdk_core
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
