name: sunny_core_widgets
version: 0.3.2+1
homepage: https://github.com/SunnyApp/sunny_core_widgets
description: Core widgets used by Sunny
environment: 
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  avoid_keyboard: ^0.3.0
  cached_network_image: ^3.2.0
  equatable: ^2.0.3
  intl: ^0.17.0
  logging: ^1.0.2
  material_segmented_control: ^3.1.2
  modal_bottom_sheet: ^2.0.1
  permission_handler: ^9.2.0
  provider: ^6.0.2
  responsive_builder: ^0.4.2
  timeago: ^3.2.2
  uri: ^1.0.0
  expanding_cards: 
    path: /Users/ericm/sunny/player_rank/packages/expanding_cards
  info_x: 
    path: /Users/ericm/sunny/player_rank/packages/info_x
  flexidate: 
    path: /Users/ericm/sunny/player_rank/packages/flexidate
  sunny_platform_widgets: 
    path: /Users/ericm/sunny/player_rank/packages/sunny_platform_widgets
  flutter_screen_scaling: 
    path: /Users/ericm/sunny/player_rank/packages/flutter_screen_scaling
  sunny_essentials: 
    path: /Users/ericm/sunny/player_rank/packages/sunny_essentials
  sunny_fluro: 
    path: /Users/ericm/sunny/player_rank/packages/sunny_fluro
  sunny_sdk_core: 
    path: /Users/ericm/sunny/player_rank/packages/sunny_sdk_core
  dartxx: 
    path: /Users/ericm/sunny/player_rank/packages/dartxx
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
