name: sunny_core_widgets
version: 0.2.0+4
homepage: https://github.com/SunnyApp/sunny_core_widgets
description: Core widgets used by Sunny
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  cached_network_image: ^3.0.0-nullsafety
  dartxx: ^0.5.0+2
  equatable: ^2.0.0
  expanding_cards: ^0.6.0+3
  flexidate: ^0.5.0+1
  flutter_platform_widgets: ^1.0.1-nullsafety.2
  flutter_screen_scaling: ^3.3.2+2
  info_x: ^0.5.0+1
  intl: ^0.17.0
  logging: ^1.0.0
  material_segmented_control: ^3.0.0-nullsafety.1
  modal_bottom_sheet: ^2.0.0
  permission_handler: ^6.1.1
  provider: ^5.0.0
  responsive_builder: ^0.4.0-nullsafety.1
  sunny_essentials: ^0.6.0+1
  sunny_fluro: ^1.8.0+1
  sunny_sdk_core: ^2.0.0+2
  timeago: ^3.0.2
  uri: ^1.0.0
  flutter: 
    sdk: flutter
dependency_overrides:
  sunny_sdk_core:
    path: ../sunny_sdk_core
dev_dependencies:
  flutter_test: 
    sdk: flutter
