name: sunny_core_widgets
version: 0.3.2+1
homepage: https://github.com/SunnyApp/sunny_core_widgets
description: Core widgets used by Sunny
environment: 
  sdk: '>=2.16.0 <3.0.0'
dependencies: 
  cached_network_image: ^3.2.0
  equatable: ^2.0.3
  expanding_cards: ^0.8.0+6
  flexidate: ^0.8.0+3
  sunny_platform_widgets: ^1.21.0
  flutter_screen_scaling: ^3.3.2+3
  info_x: ^0.8.0+3
  intl: ^0.17.0
  logging: ^1.0.2
  material_segmented_control: ^3.1.2
  modal_bottom_sheet: ^2.0.1
  permission_handler: ^9.2.0
  provider: ^6.0.2
  responsive_builder: ^0.4.2
  sunny_essentials: ^0.8.2+1
  sunny_fluro: ^1.12.0
  sunny_sdk_core: ^2.5.0
  timeago: ^3.2.2
  uri: ^1.0.0
  dartxx: ^0.5.5
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
