name: sunny_core_widgets
#version: 0.1.1+11
publish_to: none
homepage: https://github.com/SunnyApp/sunny_core_widgets
description: Core widgets used by Sunny
environment: 
  sdk: '>=2.8.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'
dependencies:
  flutter:
    sdk: flutter
  badges: ^1.1.4
  cached_network_image: ^2.4.0
  equatable: ^1.2.5
  expanding_cards: ^0.4.4
  fluro: ^1.7.8
  flutter_degen:
    path: ../flutter_degen
  flutter_platform_widgets: 0.70.2
  flutter_screen_scaling:
    path: ../flutter_screen_scaling
  logging: any
  material_segmented_control: ^2.1.0+1
  modal_bottom_sheet: ^1.0.0+1
  permission_handler: ^5.0.1+1
  provider: ^4.3.2+2
  responsive_builder: ^0.3.0
  sunny_dart: ^0.5.8+3
  sunny_sdk_core:
    path: ../sunny_sdk_core
  timeago: ^2.0.29
  uri: ^0.11.3+1
dependency_overrides:
  flutter_platform_widgets:
    path: ../flutter_platform_widgets
  waypoints:
    path: ../sunny_entities/waypoints
  sunny_sdk_core:
    path: ../sunny_sdk_core
  modal_bottom_sheet:
    path: ../modal_bottom_sheet
  fluro:
    path: ../fluro
  sunny_dart:
    path: ../sunny_dart
  expanding_cards:
    path: ../expanding_cards
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
