name: sunny_core_widgets
version: 0.1.1+9
homepage: https://github.com/SunnyApp/sunny_core_widgets
description: Core widgets used by Sunny
environment: 
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'
dependencies: 
  provider: ^4.3.2+2
  sunny_dart: ^0.5.8
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
