name: sunny_core_widgets
version: 0.3.2+1
homepage: https://github.com/SunnyApp/sunny_core_widgets
description: Core widgets used by Sunny
environment: 
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  avoid_keyboard: ^0.3.0
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  intl: ^0.18.0
  logging: ^1.1.1
  material_segmented_control: ^3.1.2
  permission_handler: ^10.2.0
  provider: ^6.0.5
  responsive_builder: ^0.5.0+1
  timeago: ^3.3.0
  modal_bottom_sheet: ^3.0.0-pre
  uri: ^1.0.0
  auto_route: 
    path: /Users/ericm/reliveit/checkout/ericmartineau/auto_route_library/auto_route
  macos_ui: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/macos_ui
  expanding_cards: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/expanding_cards
  info_x: 
    path: /Users/ericm/reliveit/checkout/ericmartineau/info_x
  flexidate: 
    path: /Users/ericm/reliveit/checkout/ericmartineau/flexidate
  sunny_platform_widgets: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/flutter_platform_widgets
  flutter_screen_scaling: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/flutter_screen_scaling
  sunny_essentials: 
    path: /Users/ericm/reliveit/checkout/ericmartineau/sunny_essentials
  sunny_sdk_core: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/sunny_sdk_core
  dartxx: 
    path: /Users/ericm/reliveit/checkout/ericmartineau/dartxx
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
