name: sunny_core_widgets
version: 0.1.1+13
homepage: https://github.com/SunnyApp/sunny_core_widgets
description: Core widgets used by Sunny
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cached_network_image: ^3.0.0-nullsafety
  equatable: ^2.0.0
  intl: ^0.17.0
  expanding_cards: ^0.5.1-nullsafety.7
  sunny_fluro: ^1.8.0-nullsafe.2
  flexidate: ^0.4.5-nullsafety.2
  flutter_platform_widgets: ^1.0.1-nullsafety.2
  flutter_screen_scaling: ^3.3.2+1
  logging: ^1.0.0
  info_x: ^0.4.4-nullsafety.1
  material_segmented_control: ^3.0.0-nullsafety.1
  dartxx: ^0.4.5-nullsafety.5
  sunny_essentials: ^0.4.4-nullsafety.4
  modal_bottom_sheet: ^2.0.0
  permission_handler: ^6.1.1
  provider: ^5.0.0
  responsive_builder: ^0.4.0-nullsafety.1
  sunny_sdk_core: ^2.0.0-nullsafe.16
  uri: ^1.0.0
  flutter: 
    sdk: flutter
dev_dependencies:
  flutter_test: 
    sdk: flutter
